name: YOLO CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: pytest tests/

    - name: Build Docker image
      run: docker build -t my-yolo-app .

    - name: Push Docker image
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker tag my-yolo-app my-dockerhub-username/my-yolo-app:latest
        docker push my-dockerhub-username/my-yolo-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker pull my-dockerhub-username/my-yolo-app:latest
          docker stop yolo || true
          docker rm yolo || true
          docker run -d -p 5000:5000 --name yolo my-dockerhub-username/my-yolo-app:latest

          
